package export

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/wootaiklee/git-resume/pkg/models"
)

// MarkdownExporter exports analysis results to Markdown format
type MarkdownExporter struct {
	outputDir string
}

// NewMarkdownExporter creates a new Markdown exporter
func NewMarkdownExporter(outputDir string) *MarkdownExporter {
	return &MarkdownExporter{outputDir: outputDir}
}

// Export writes results to a Markdown file
func (e *MarkdownExporter) Export(results []models.AnalysisResult, filename string) (string, error) {
	if err := os.MkdirAll(e.outputDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create output directory: %w", err)
	}

	outputPath := filepath.Join(e.outputDir, filename)
	file, err := os.Create(outputPath)
	if err != nil {
		return "", fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	// Group results by category
	grouped := groupByCategory(results)

	// Write header
	var sb strings.Builder
	sb.WriteString("# Resume Achievements\n\n")
	sb.WriteString(fmt.Sprintf("*Generated from %d commits*\n\n", len(results)))

	// Write date range
	if len(results) > 0 {
		minDate, maxDate := getDateRange(results)
		sb.WriteString(fmt.Sprintf("**Period:** %s to %s\n\n",
			minDate.Format("January 2, 2006"),
			maxDate.Format("January 2, 2006")))
	}

	sb.WriteString("---\n\n")

	// Write each category
	categoryOrder := []models.Category{
		models.CategoryFeature,
		models.CategoryFix,
		models.CategoryRefactor,
		models.CategoryTest,
		models.CategoryDocs,
		models.CategoryChore,
	}

	for _, cat := range categoryOrder {
		if items, ok := grouped[cat]; ok && len(items) > 0 {
			sb.WriteString(fmt.Sprintf("## %s %s\n\n", getCategoryEmoji(cat), cat))

			for _, item := range items {
				sb.WriteString(fmt.Sprintf("- **%s** %s\n",
					item.Date.Format("2006-01-02"),
					item.ImpactSummary))
				if item.Project != "" {
					sb.WriteString(fmt.Sprintf("  - *Project: %s* | `%s`\n",
						item.Project, item.CommitHash[:7]))
				}
			}
			sb.WriteString("\n")
		}
	}

	// Write footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by [git-resume](https://github.com/wootaiklee/git-resume)*\n")

	if _, err := file.WriteString(sb.String()); err != nil {
		return "", fmt.Errorf("failed to write content: %w", err)
	}

	return outputPath, nil
}

// ExportWithTimestamp exports with automatic timestamp in filename
func (e *MarkdownExporter) ExportWithTimestamp(results []models.AnalysisResult, prefix string) (string, error) {
	if len(results) == 0 {
		return "", fmt.Errorf("no results to export")
	}

	minDate, maxDate := getDateRange(results)
	filename := fmt.Sprintf("%s_%s_to_%s.md",
		prefix,
		minDate.Format("2006-01-02"),
		maxDate.Format("2006-01-02"),
	)

	return e.Export(results, filename)
}

func groupByCategory(results []models.AnalysisResult) map[models.Category][]models.AnalysisResult {
	grouped := make(map[models.Category][]models.AnalysisResult)

	for _, r := range results {
		grouped[r.Category] = append(grouped[r.Category], r)
	}

	// Sort each group by date (newest first)
	for cat := range grouped {
		sort.Slice(grouped[cat], func(i, j int) bool {
			return grouped[cat][i].Date.After(grouped[cat][j].Date)
		})
	}

	return grouped
}

func getCategoryEmoji(cat models.Category) string {
	switch cat {
	case models.CategoryFeature:
		return "✨"
	case models.CategoryFix:
		return "🐛"
	case models.CategoryRefactor:
		return "♻️"
	case models.CategoryTest:
		return "🧪"
	case models.CategoryDocs:
		return "📚"
	case models.CategoryChore:
		return "🔧"
	default:
		return "📌"
	}
}
